accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/',views.SignUpView.as_view(),name='signup'),
]

importantLog/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('logapp.urls')),
    path('accounts/',include('accounts.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

logapp/urls.py
from django.urls import path
from . import views

app_name = 'logapp'

urlpatterns = [
    path('',views.top_page,name='top_page'),
    path('lists/',views.lists,name='lists'),
    path('lists/<int:pk>',views.log_detail,name='log_detail'),
    path('usertitle/',views.user_title,name="user_title"),
    path('new_title/',views.new_title,name='new_title'),
    path('edit_title/<int:pk>',views.edit_title,name='edit_title'),
    path('user_detail<int:pk>',views.user_detail,name='user_detail'),
    path('delete/<int:pk>',views.delete,name='delete'),
    path('good/<int:pk>',views.good,name='good'),
]

accounts/models.py
from django.db import models

logapp/models.py
from django.db import models
from django.utils import timezone

class Log(models.Model):
    user = models.ForeignKey('auth.User',on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.title

logapp/forms.py
from django import forms
from .models import Log

class PostForm(forms.ModelForm):
    class Meta:
        model = Log
        fields = ('title','text')

accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

logapp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from .models import Log
from django.contrib.auth.models import User
from .forms import PostForm

def top_page(request):
    return render(request,'logapp/top.html',{})

def lists(request):
    logs = Log.objects.all()
    ranking = Log.objects.all().order_by('votes').reverse()
    newtitle = Log.objects.all().order_by('created_date').reverse()
    return render(request,'logapp/lists.html',{'logs':logs,'ranking':ranking,'newtitle':newtitle})

def log_detail(request,pk):
    logs = get_object_or_404(Log,pk=pk)
    return render(request,'logapp/detail.html',{'logs':logs})

def user_detail(request,pk):
    logs = get_object_or_404(Log,pk=pk)
    return render(request,'logapp/user_detail.html',{'logs':logs})

def user_title(request):
    me = request.user
    logs = Log.objects.filter(user=me)
    return render(request,'logapp/user_title.html',{'logs':logs})

def new_title(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            logs = form.save(commit=False)
            logs.user = request.user
            logs.save()
            return redirect('logapp:lists')
    else:
        form = PostForm()
    return render(request,'logapp/new_title.html',{'form':form})


def edit_title(request,pk):
    log = get_object_or_404(Log,pk=pk)
    if request.method == 'POST':
        form = PostForm(request.POST,instance=log)
        if form.is_valid():
            logs = form.save(commit=False)
            logs.user = request.user
            logs.save()
            return redirect('logapp:lists')
    else:
        form = PostForm(instance=log)
    return render(request,'logapp/edit_title.html',{'form':form})

def delete(request,pk):
    logs = get_object_or_404(Log,pk=pk)
    logs.delete()
    return redirect('logapp:lists')

def good(request,pk):
    logs = get_object_or_404(Log,pk=pk)
    logs.votes += 1
    logs.save()
    return redirect('logapp:log_detail',pk=logs.pk)

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>新規登録</h1>
<section class="common-form">
  <form method="post">
    {% csrf_token %}
    {{ form.as_p}}
    <button type="submit" class="submit">新規登録</button>
  </form>
</section>
{% endblock %}

logapp/templates/logapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>「IpLog」日常の「これは大事なこと」を共有</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <header>
      <div class="logo">
        <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
      </div>
      <div class="nav">
        <ul class="global-nav">
          {% if  user.is_authenticated %}
            <li class="login-txt">{{ user.get_username }}がログイン中</li>
            <li><a href="{% url 'logout' %}">ログアウト</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">ログイン</a></li>
            <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main id="base">
      <div class="contents">

      </div>
    </main>
    <footer>
      <small>(c)2019 shogo kato</small>
    </footer>
  </body>
</html>

logapp/templates/logapp/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>「IpLog」詳細ページ</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body id="detail">
    <header>
      <div class="logo">
        <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
      </div>
      <div class="nav">
        <ul class="global-nav">
          {% if  user.is_authenticated %}
            <li class="login-txt">{{ user.get_username }}がログイン中</li>
            <li><a href="{% url 'logout' %}">ログアウト</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">ログイン</a></li>
            <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main id="base" class="clearfix">
      <div class="contents">
        <div class="main">
          <h1>詳細ページ</h1>
          <p>タイトル一覧で選んだ投稿の詳細が見れます。</p>
          <section>
            <h2>{{ logs.title }}</h2>
            <p>{{ logs.text|linebreaksbr}}</p>
            <p>{{ logs.user }} {{ logs.created_date }}</p>
            <p>いいね:{{ logs.votes }}件</p>
            <a href="{% url 'logapp:good' pk=logs.pk %}"><img src="{% static 'image/votes.png' %}"></a>
          </section>
        </div>
        <aside class="sidebar">
          <section>
            <h2>タイトルメニュー</h2>
            <li><a href="{% url 'logapp:lists' %}#newtitle">最新タイトル</a></li>
            <li><a href="{% url 'logapp:lists' %}#ranking">人気タイトル</a></li>
            <li><a href="{% url 'logapp:lists' %}#hoge">タイトル一覧</a></li>
          </section>
          <section>
            {% if user.is_authenticated %}
              <h2>ユーザーメニュー</h2>
              <li><a href="{% url 'logapp:user_title' %}">ユーザーの投稿</a></li>
              <li><a href="{% url 'logapp:new_title' %}">新規投稿</a></li>
            {% endif %}
          </section>
        </aside>
      </div>
    </main>
    <footer>
      <small>(c)2019 shogo kato</small>
    </footer>
  </body>
</html>

logapp/templates/logapp/edit_title.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>「IpLog」編集ページ</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body id="edit">
    <header>
      <div class="logo">
        <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
      </div>
      <div class="nav">
        <ul class="global-nav">
          {% if  user.is_authenticated %}
            <li class="login-txt">{{ user.get_username }}がログイン中</li>
            <li><a href="{% url 'logout' %}">ログアウト</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">ログイン</a></li>
            <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main id="base">
      <div class="contents">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">保存</button>
        </form>
      </div>
    </main>
    <footer>
      <small>(c)2019 shogo kato</small>
    </footer>
  </body>
</html>

logapp/templates/logapp/lists.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>「IpLog」タイトル一覧</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body id="lists">
    <header>
      <div class="logo">
        <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
      </div>
      <div class="nav">
        <ul class="global-nav">
          {% if  user.is_authenticated %}
            <li class="login-txt">{{ user.get_username }}がログイン中</li>
            <li><a href="{% url 'logout' %}">ログアウト</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">ログイン</a></li>
            <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main id="base">
      <div class="contents">
        <div class="new-title">
          <h1>タイトル一覧</h1>
          <p>「ImLog」投稿一覧です。</p>
          <section class="profile clearfix">
            <div class="main">
              <div class="lists-text">
                <h2 class="icon" id="newtitle">最新のタイトル</h2>
                {% for new in newtitle %}
                  {% if not forloop.counter > 5 %}
                    <p><a href="{% url 'logapp:log_detail' pk=new.pk %}">{{ new.title }}</a> 投稿日：{{ new.created_date }}</p>
                  {% else %}
                      <p></p>
                  {% endif %}
                {% endfor %}
              </div>
              <div class="ranking" id="ranking">
                <h2 class="icon">人気のタイトル</h2>
                {% for rank in ranking %}
                  {% if not forloop.counter > 3 %}
                    <p>{{ forloop.counter }}位:<a href="{% url 'logapp:log_detail' pk=rank.pk %}">{{ rank.title }}</a> いいね：{{ rank.votes }}</p>
                  {% else %}
                    <p></p>
                  {% endif %}
                {% endfor %}
              </div>
              <div class="lists">
                <h2 class="icon" id="hoge">タイトル一覧</h2>
                {% for log in logs %}
                  <p><a href="{% url 'logapp:log_detail' pk=log.pk %}">{{ log.title }}</a></p>
                {% endfor %}
              </div>
            </div>
              <aside class="sidebar">
                <section>
                  <h2>タイトルメニュー</h2>
                  <li><a href="#newtitle">最新タイトル</a></li>
                  <li><a href="#ranking">人気タイトル</a></li>
                  <li><a href="#hoge">タイトル一覧</a></li>
                </section>
                <section>
                  {% if user.is_authenticated %}
                    <h2>ユーザーメニュー</h2>
                    <li><a href="{% url 'logapp:user_title' %}">ユーザーの投稿</a></li>
                    <li><a href="{% url 'logapp:new_title' %}">新規投稿</a></li>
                  {% endif %}
                </section>
              </aside>
          </section>
        </div>
      </div>
    </main>
    <footer>
      <small>(c)2019 shogo kato</small>
    </footer>
  </body>
</html>

logapp/templates/logapp/new_title.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>「IpLog」新規投稿</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body id="edit">
    <header>
      <div class="logo">
        <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
      </div>
      <div class="nav">
        <ul class="global-nav">
          {% if  user.is_authenticated %}
            <li class="login-txt">{{ user.get_username }}がログイン中</li>
            <li><a href="{% url 'logout' %}">ログアウト</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">ログイン</a></li>
            <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main id="base">
      <div class="contents">
        <h1>新規投稿ページ</h1>
        <p>タイトルと本文を入力してください。</p>
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit">保存</button>
        </form>
      </div>
    </main>
    <footer>
      <small>(c)2019 shogo kato</small>
    </footer>
  </body>
</html>

logapp/templates/logapp/top.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>「ImLog」トップベージ</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body id="top">
    <header>
      <div class="logo">
        <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
      </div>
      <div class="nav">
        <ul class="global-nav">
          {% if user.is_authenticated %}
            <li class="login-txt">{{ user.get_username }}がログイン中</li>
            <li><a href="{% url 'logout' %}">ログアウト</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">ログイン</a></li>
            <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main id="base">
      <div class="contents">
        <h1>「ImLog」で大事なことを共有しよう</h1>
        <p>このWebサイトは、駆け出しエンジニアである加藤彰悟が、日常の「これは大事なこと」を共有することをコンセプトを
          テーマに<br>手がけたログアプリです。皆さんの「これは大事なこと」を共有してたくさんの考えを広めていきましょう。</p>
        <p class="btn"><a href="{% url 'logapp:lists' %}">ImLogを始める</a></p>
      </div>
    </main>
    <footer>
      <small>(c)2019 shogo kato</small>
    </footer>
  </body>
</html>

logapp/templates/logapp/user_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>「IpLog」詳細ページ</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body id="detail">
    <header>
      <div class="logo">
        <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
      </div>
      <div class="nav">
        <ul class="global-nav">
          {% if  user.is_authenticated %}
            <li class="login-txt">{{ user.get_username }}がログイン中</li>
            <li><a href="{% url 'logout' %}">ログアウト</a></li>
          {% else %}
            <li><a href="{% url 'login' %}">ログイン</a></li>
            <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
          {% endif %}
        </ul>
      </div>
    </header>
    <main id="base" class="clearfix">
      <div class="contents">
        <div class="main">
          <h1>詳細ページ</h1>
          <p>タイトル一覧で選んだ投稿の詳細が見れます。</p>
          <section>
            <h2>{{ logs.title }}</h2>
            <p>{{ logs.text|linebreaksbr}}</p>
            <p>{{ logs.user }} {{ logs.created_date }}</p>
            <p>いいね:{{ logs.votes }}件</p>
          </section>
          {% if user.is_authenticated %}
            <a class="btn btn-default" href="{% url 'logapp:edit_title' pk=logs.pk %}"><span class="glyphicon-pencil"></span></a>
          {% endif %}
          <a href="{% url 'logapp:delete' pk=logs.pk %}"><img src="{% static 'image/delete.png' %}"></a>
        </div>
        <aside class="sidebar">
          <section>
            <h2>タイトルメニュー</h2>
            <li><a href="{% url 'logapp:lists' %}#newtitle">最新タイトル</a></li>
            <li><a href="{% url 'logapp:lists' %}#ranking">人気タイトル</a></li>
            <li><a href="{% url 'logapp:lists' %}#hoge">タイトル一覧</a></li>
          </section>
          <section>
            {% if user.is_authenticated %}
              <h2>ユーザーメニュー</h2>
              <li><a href="{% url 'logapp:user_title' %}">ユーザーの投稿</a></li>
              <li><a href="{% url 'logapp:new_title' %}">新規投稿</a></li>
            {% endif %}
          </section>
        </aside>
      </div>
    </main>
    <footer>
      <small>(c)2019 shogo kato</small>
    </footer>
  </body>
</html>

logapp/templates/logapp/user_title.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>「IpLog」日常の「これは大事なこと」を共有</title>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body id ="userlists">
    <header>
      <div class="logo">
        <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
      </div>
      <div class="nav">
        <ul class="global-nav">
        <li class="login-txt">{{ user.get_username }}がログイン中</li>
        <li><a href="{% url 'logout' %}">ログアウト</a></li>
        </ul>
      </div>
    </header>
    <main id="base">
      <div class="contents">
        <div class="new-title">
        <h1>ユーザータイトル一覧</h1>
        <p>「ImLog」投稿一覧です。</p>
        <section class="profile clearfix">
          <div class="main">
            <div class="lists">
              <h2 class="icon">{{ user.get_username }}のタイトル一覧</h2>
              {% for log in logs %}
                <p><a href="{% url 'logapp:user_detail' pk=log.pk %}">{{ log.title }}</a></p>
              {% endfor %}
            </div>
          </div>
            <aside class="sidebar">
              <section>
                <h2>タイトルメニュー</h2>
                <li><a href="{% url 'logapp:lists' %}#newtitle">最新タイトル</a></li>
                <li><a href="{% url 'logapp:lists' %}#ranking">人気タイトル</a></li>
                <li><a href="{% url 'logapp:lists' %}#hoge">タイトル一覧</a></li>
              </section>
              <section>
                <h2>ユーザーメニュー</h2>
                <li><a href="{% url 'logapp:user_title' %}">ユーザーの投稿</a></li>
                <li><a href="{% url 'logapp:new_title' %}">新規投稿</a></li>
              </section>
            </aside>
        </section>
      </div>
    </div>
  </main>
  <footer>
    <small>(c)2019 shogo kato</small>
  </footer>
</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body id="loginout">
<header>
  <div class="logo">
    <a href="{% url 'logapp:top_page' %}"><img src="{% static 'image/logo.png' %}" alt="ImLog"></a>
  </div>
    <div class="nav">
      <ul class="global-nav">
        {% if  user.is_authenticated %}
          <li class="login-txt">{{ user.get_username }}がログイン中</li>
          <li><a href="{% url 'logout' %}">ログアウト</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">ログイン</a></li>
          <li><a href="{% url 'accounts:signup' %}">新規登録</a></li>
        {% endif %}
      </ul>
    </div>
</header>
<main id="base">
  <div class="contents">
      {% block content %}{% endblock %}
  </div>
</main>
<footer>
  <small>(c)2019 shogo kato</small>
</footer>
</body>
</html>